OAuth
SashaLevkovich/middle.SandwormRampage.praktikum.yandex pull request #75
Opened 2024-07-11 08:39 UTC by Pillowbee

### Какую задачу решаем
Добавить OAuth-авторизацию в проект

2024-07-11 10:55 UTC, SashaLevkovich approved these changes

2024-07-11 14:13 UTC, divnvp approved these changes

2024-07-11 14:19 UTC, VlAnton approved these changes

2024-07-12 20:28 UTC, IvanPeleshok requested changes
Добрый вечер
Отлично потрудились
Оставил пару замечаний, предлагаю ознакомиться и поправить :)

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/app/api/requests/oAuth.ts
> +const oAuthUrlBase = 'https://oauth.yandex.ru/authorize'
Отличный кандидат для того, чтобы вынести в переменную окружения (необязательно, рекомендация) https://forum.freecodecamp.org/t/how-to-use-environment-variables-in-frontend/458076

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +    if (window && window.location.search.match('code') !== null) {
if (!window?.location.search.match('code')) {

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +      const data: { [index: string]: string } = {}
const data: Record<string, string>

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +        authRequests.getUser().then(resp => {
Предлагаю пользоваться последним синтаксисом try / catch + async / await
Также предлагаю не сокращать наименование переменных, т.к код пишется для команды разработчиков `response`
```
const getUser = async () => {
  try {
    const { data } = await authRequests.getUser()
    setLocalStorageUser(data)
  } catch (ex) {
    console.log(ex) // handle exception
  }

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +        .oAuthSignIn(data['code'])
Аналогично, try / catch + async / await
response

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +          if (resp.status === 200) {
200 / 400 вынести в перменные с контекстным названием (можно переиспользовать)

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/signIn/SignIn.tsx
> +    } else {
Предлагаю избегать ветвление в коде, если возможно и пользоваться ранним выходом
```
if (cond) {
  ...
  return
}
//else

2024-07-12 20:28 UTC, IvanPeleshok commented on packages/client/src/pages/gameStart/GameStart.tsx
> +      const oAuthParamsStringsArr = window.location.search.slice(1).split('&')
Предлагаю логику парсинга вынести в отдельный хелпер (проще тестировать, декомпозиция)

2024-07-13 07:22 UTC, IvanPeleshok approved these changes
Всё супер
Поздравляю, работа принята 🚀 
Хорошего дня :)

2024-07-13 08:08 UTC, merged